name: Build project
on: [ push ]
jobs:
  build:
    name: Build
    runs-on: node-alpine
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Build
        run: |
          docker build -t ms-test-app .
      -
        name: Test
        run: |
          docker run -dp 8080:8080 -e GREETING_NAME=Alex ms-test-app
          # wait for container ready
          sleep 30
          greeting=$(curl -s http://localhost:8080)
          if [ "$greeting" != "Hello, Alex" ]; then
            echo "Expected [Hello, Alex], but greeting from docker [$greeting] doesn't macthes"
            exit 1
          fi